pipeline:
  build:
    image: node:10
    commands:
      - yarn
      - yarn test
  docker:
    image: plugins/docker
    repo: bitsler/wallet-alert
    tags: latest
    secrets: [ docker_username, docker_password ]